
language: generic 

# Need super user perms.
sudo: required

# Docker must be installed.
services:
    - docker

# Executed before tests executed.
before_install:
    - docker build -t scramsay051200/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true scramsay051200/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region:  "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-657749227937"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
