
language: generic 

# Need super user perms.
sudo: required

# Docker must be installed.
services:
    - docker

# Executed before tests executed.
before_install:
    - docker build -t scramsay051200/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true scramsay051200/docker-react npm run test
